package model;

// Generated 2015-12-11 16:56:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExpertInfo generated by hbm2java
 */
@Entity
@Table(name = "expert_info")
public class ExpertInfo implements java.io.Serializable {

	private int userId;
	private String name;
	private String education;
	private String workPlace;
	private String postcode;
	private String techLevel;
	private Integer techWorkYears;
	private String telephone;
	private String mail;
	private Integer hasFillSurvey;
	private String administrationDuty;
	private Integer goodatArea1;
	private String area1Major;
	private Integer area1Year;
	private Integer goodatArea2;
	private String area2Major;
	private Integer area2Year;
	private Integer goodatArea3;
	private String area3Major;
	private Integer area3Year;
	private Integer goodatArea4;
	private String area4Major;
	private Integer area4Year;
	private Integer goodatArea5;
	private String area5Major;
	private Integer area5Year;
	private Integer age;
	private Integer administrationWorkYear;
	private int hasFillSurvey2;
	private int hasFillBankinfo;

	public ExpertInfo() {
	}

	public ExpertInfo(int userId, int hasFillSurvey2, int hasFillBankinfo) {
		this.userId = userId;
		this.hasFillSurvey2 = hasFillSurvey2;
		this.hasFillBankinfo = hasFillBankinfo;
	}

	public ExpertInfo(int userId, String name, String education,
			String workPlace, String postcode, String techLevel,
			Integer techWorkYears, String telephone, String mail,
			Integer hasFillSurvey, String administrationDuty,
			Integer goodatArea1, String area1Major, Integer area1Year,
			Integer goodatArea2, String area2Major, Integer area2Year,
			Integer goodatArea3, String area3Major, Integer area3Year,
			Integer goodatArea4, String area4Major, Integer area4Year,
			Integer goodatArea5, String area5Major, Integer area5Year,
			Integer age, Integer administrationWorkYear, int hasFillSurvey2,
			int hasFillBankinfo) {
		this.userId = userId;
		this.name = name;
		this.education = education;
		this.workPlace = workPlace;
		this.postcode = postcode;
		this.techLevel = techLevel;
		this.techWorkYears = techWorkYears;
		this.telephone = telephone;
		this.mail = mail;
		this.hasFillSurvey = hasFillSurvey;
		this.administrationDuty = administrationDuty;
		this.goodatArea1 = goodatArea1;
		this.area1Major = area1Major;
		this.area1Year = area1Year;
		this.goodatArea2 = goodatArea2;
		this.area2Major = area2Major;
		this.area2Year = area2Year;
		this.goodatArea3 = goodatArea3;
		this.area3Major = area3Major;
		this.area3Year = area3Year;
		this.goodatArea4 = goodatArea4;
		this.area4Major = area4Major;
		this.area4Year = area4Year;
		this.goodatArea5 = goodatArea5;
		this.area5Major = area5Major;
		this.area5Year = area5Year;
		this.age = age;
		this.administrationWorkYear = administrationWorkYear;
		this.hasFillSurvey2 = hasFillSurvey2;
		this.hasFillBankinfo = hasFillBankinfo;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "education", length = 20)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "work_place", length = 50)
	public String getWorkPlace() {
		return this.workPlace;
	}

	public void setWorkPlace(String workPlace) {
		this.workPlace = workPlace;
	}

	@Column(name = "postcode", length = 20)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "tech_level", length = 20)
	public String getTechLevel() {
		return this.techLevel;
	}

	public void setTechLevel(String techLevel) {
		this.techLevel = techLevel;
	}

	@Column(name = "tech_work_years")
	public Integer getTechWorkYears() {
		return this.techWorkYears;
	}

	public void setTechWorkYears(Integer techWorkYears) {
		this.techWorkYears = techWorkYears;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "mail", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "has_fill_survey")
	public Integer getHasFillSurvey() {
		return this.hasFillSurvey;
	}

	public void setHasFillSurvey(Integer hasFillSurvey) {
		this.hasFillSurvey = hasFillSurvey;
	}

	@Column(name = "administration_duty", length = 20)
	public String getAdministrationDuty() {
		return this.administrationDuty;
	}

	public void setAdministrationDuty(String administrationDuty) {
		this.administrationDuty = administrationDuty;
	}

	@Column(name = "goodat_area_1")
	public Integer getGoodatArea1() {
		return this.goodatArea1;
	}

	public void setGoodatArea1(Integer goodatArea1) {
		this.goodatArea1 = goodatArea1;
	}

	@Column(name = "area_1_major", length = 50)
	public String getArea1Major() {
		return this.area1Major;
	}

	public void setArea1Major(String area1Major) {
		this.area1Major = area1Major;
	}

	@Column(name = "area_1_year")
	public Integer getArea1Year() {
		return this.area1Year;
	}

	public void setArea1Year(Integer area1Year) {
		this.area1Year = area1Year;
	}

	@Column(name = "goodat_area_2")
	public Integer getGoodatArea2() {
		return this.goodatArea2;
	}

	public void setGoodatArea2(Integer goodatArea2) {
		this.goodatArea2 = goodatArea2;
	}

	@Column(name = "area_2_major", length = 50)
	public String getArea2Major() {
		return this.area2Major;
	}

	public void setArea2Major(String area2Major) {
		this.area2Major = area2Major;
	}

	@Column(name = "area_2_year")
	public Integer getArea2Year() {
		return this.area2Year;
	}

	public void setArea2Year(Integer area2Year) {
		this.area2Year = area2Year;
	}

	@Column(name = "goodat_area_3")
	public Integer getGoodatArea3() {
		return this.goodatArea3;
	}

	public void setGoodatArea3(Integer goodatArea3) {
		this.goodatArea3 = goodatArea3;
	}

	@Column(name = "area_3_major", length = 50)
	public String getArea3Major() {
		return this.area3Major;
	}

	public void setArea3Major(String area3Major) {
		this.area3Major = area3Major;
	}

	@Column(name = "area_3_year")
	public Integer getArea3Year() {
		return this.area3Year;
	}

	public void setArea3Year(Integer area3Year) {
		this.area3Year = area3Year;
	}

	@Column(name = "goodat_area_4")
	public Integer getGoodatArea4() {
		return this.goodatArea4;
	}

	public void setGoodatArea4(Integer goodatArea4) {
		this.goodatArea4 = goodatArea4;
	}

	@Column(name = "area_4_major", length = 50)
	public String getArea4Major() {
		return this.area4Major;
	}

	public void setArea4Major(String area4Major) {
		this.area4Major = area4Major;
	}

	@Column(name = "area_4_year")
	public Integer getArea4Year() {
		return this.area4Year;
	}

	public void setArea4Year(Integer area4Year) {
		this.area4Year = area4Year;
	}

	@Column(name = "goodat_area_5")
	public Integer getGoodatArea5() {
		return this.goodatArea5;
	}

	public void setGoodatArea5(Integer goodatArea5) {
		this.goodatArea5 = goodatArea5;
	}

	@Column(name = "area_5_major", length = 50)
	public String getArea5Major() {
		return this.area5Major;
	}

	public void setArea5Major(String area5Major) {
		this.area5Major = area5Major;
	}

	@Column(name = "area_5_year")
	public Integer getArea5Year() {
		return this.area5Year;
	}

	public void setArea5Year(Integer area5Year) {
		this.area5Year = area5Year;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "administration_work_year")
	public Integer getAdministrationWorkYear() {
		return this.administrationWorkYear;
	}

	public void setAdministrationWorkYear(Integer administrationWorkYear) {
		this.administrationWorkYear = administrationWorkYear;
	}

	@Column(name = "has_fill_survey2", nullable = false)
	public int getHasFillSurvey2() {
		return this.hasFillSurvey2;
	}

	public void setHasFillSurvey2(int hasFillSurvey2) {
		this.hasFillSurvey2 = hasFillSurvey2;
	}

	@Column(name = "has_fill_bankinfo", nullable = false)
	public int getHasFillBankinfo() {
		return this.hasFillBankinfo;
	}

	public void setHasFillBankinfo(int hasFillBankinfo) {
		this.hasFillBankinfo = hasFillBankinfo;
	}

}
