package model;

// Generated 2015-12-11 16:56:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InitialExpertInfo generated by hbm2java
 */
@Entity
@Table(name = "initial_expert_info")
public class InitialExpertInfo implements java.io.Serializable {

	private Integer id;
	private String mail;
	private String name;
	private String workplace;
	private int isUsed;

	public InitialExpertInfo() {
	}

	public InitialExpertInfo(int isUsed) {
		this.isUsed = isUsed;
	}

	public InitialExpertInfo(String mail, String name, String workplace,
			int isUsed) {
		this.mail = mail;
		this.name = name;
		this.workplace = workplace;
		this.isUsed = isUsed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mail", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "workplace", length = 50)
	public String getWorkplace() {
		return this.workplace;
	}

	public void setWorkplace(String workplace) {
		this.workplace = workplace;
	}

	@Column(name = "is_used", nullable = false)
	public int getIsUsed() {
		return this.isUsed;
	}

	public void setIsUsed(int isUsed) {
		this.isUsed = isUsed;
	}

}
