package model;

// Generated 2015-12-11 16:56:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Remark2Id generated by hbm2java
 */
@Embeddable
public class Remark2Id implements java.io.Serializable {

	private int userId;
	private int secondLevelId;

	public Remark2Id() {
	}

	public Remark2Id(int userId, int secondLevelId) {
		this.userId = userId;
		this.secondLevelId = secondLevelId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "second_level_id", nullable = false)
	public int getSecondLevelId() {
		return this.secondLevelId;
	}

	public void setSecondLevelId(int secondLevelId) {
		this.secondLevelId = secondLevelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Remark2Id))
			return false;
		Remark2Id castOther = (Remark2Id) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getSecondLevelId() == castOther.getSecondLevelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getSecondLevelId();
		return result;
	}

}
