package model;

// Generated 2015-12-11 16:56:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Remark generated by hbm2java
 */
@Entity
@Table(name = "remark")
public class Remark implements java.io.Serializable {

	private RemarkId id;
	private Integer familiar;
	private Integer importance;
	private Integer control;
	private int selected;
	private String sickname;
	private Integer firstLevelId;

	public Remark() {
	}

	public Remark(RemarkId id, int selected) {
		this.id = id;
		this.selected = selected;
	}

	public Remark(RemarkId id, Integer familiar, Integer importance,
			Integer control, int selected, String sickname, Integer firstLevelId) {
		this.id = id;
		this.familiar = familiar;
		this.importance = importance;
		this.control = control;
		this.selected = selected;
		this.sickname = sickname;
		this.firstLevelId = firstLevelId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "secondLevelId", column = @Column(name = "second_level_id", nullable = false)) })
	public RemarkId getId() {
		return this.id;
	}

	public void setId(RemarkId id) {
		this.id = id;
	}

	@Column(name = "familiar")
	public Integer getFamiliar() {
		return this.familiar;
	}

	public void setFamiliar(Integer familiar) {
		this.familiar = familiar;
	}

	@Column(name = "importance")
	public Integer getImportance() {
		return this.importance;
	}

	public void setImportance(Integer importance) {
		this.importance = importance;
	}

	@Column(name = "control")
	public Integer getControl() {
		return this.control;
	}

	public void setControl(Integer control) {
		this.control = control;
	}

	@Column(name = "selected", nullable = false)
	public int getSelected() {
		return this.selected;
	}

	public void setSelected(int selected) {
		this.selected = selected;
	}

	@Column(name = "sickname", length = 100)
	public String getSickname() {
		return this.sickname;
	}

	public void setSickname(String sickname) {
		this.sickname = sickname;
	}

	@Column(name = "first_level_id")
	public Integer getFirstLevelId() {
		return this.firstLevelId;
	}

	public void setFirstLevelId(Integer firstLevelId) {
		this.firstLevelId = firstLevelId;
	}

}
