package model;

// Generated 2015-12-11 16:56:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SecondLevel generated by hbm2java
 */
@Entity
@Table(name = "second_level")
public class SecondLevel implements java.io.Serializable {

	private Integer id;
	private Integer firstLevelId;
	private String name;
	private Integer count;
	private int totalFamiliar;
	private int totalImportance;
	private int totalControll;
	private double ave;
	private double areaAve;
	private double percentage;
	private double aveIm;
	private double areaAveIm;
	private double aveCon;
	private double areaAveCon;

	public SecondLevel() {
	}

	public SecondLevel(int totalFamiliar, int totalImportance,
			int totalControll, double ave, double areaAve, double percentage,
			double aveIm, double areaAveIm, double aveCon, double areaAveCon) {
		this.totalFamiliar = totalFamiliar;
		this.totalImportance = totalImportance;
		this.totalControll = totalControll;
		this.ave = ave;
		this.areaAve = areaAve;
		this.percentage = percentage;
		this.aveIm = aveIm;
		this.areaAveIm = areaAveIm;
		this.aveCon = aveCon;
		this.areaAveCon = areaAveCon;
	}

	public SecondLevel(Integer firstLevelId, String name, Integer count,
			int totalFamiliar, int totalImportance, int totalControll,
			double ave, double areaAve, double percentage, double aveIm,
			double areaAveIm, double aveCon, double areaAveCon) {
		this.firstLevelId = firstLevelId;
		this.name = name;
		this.count = count;
		this.totalFamiliar = totalFamiliar;
		this.totalImportance = totalImportance;
		this.totalControll = totalControll;
		this.ave = ave;
		this.areaAve = areaAve;
		this.percentage = percentage;
		this.aveIm = aveIm;
		this.areaAveIm = areaAveIm;
		this.aveCon = aveCon;
		this.areaAveCon = areaAveCon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "first_level_id")
	public Integer getFirstLevelId() {
		return this.firstLevelId;
	}

	public void setFirstLevelId(Integer firstLevelId) {
		this.firstLevelId = firstLevelId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "total_familiar", nullable = false)
	public int getTotalFamiliar() {
		return this.totalFamiliar;
	}

	public void setTotalFamiliar(int totalFamiliar) {
		this.totalFamiliar = totalFamiliar;
	}

	@Column(name = "total_importance", nullable = false)
	public int getTotalImportance() {
		return this.totalImportance;
	}

	public void setTotalImportance(int totalImportance) {
		this.totalImportance = totalImportance;
	}

	@Column(name = "total_controll", nullable = false)
	public int getTotalControll() {
		return this.totalControll;
	}

	public void setTotalControll(int totalControll) {
		this.totalControll = totalControll;
	}

	@Column(name = "ave", nullable = false, precision = 22, scale = 0)
	public double getAve() {
		return this.ave;
	}

	public void setAve(double ave) {
		this.ave = ave;
	}

	@Column(name = "area_ave", nullable = false, precision = 22, scale = 0)
	public double getAreaAve() {
		return this.areaAve;
	}

	public void setAreaAve(double areaAve) {
		this.areaAve = areaAve;
	}

	@Column(name = "percentage", nullable = false, precision = 22, scale = 0)
	public double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(double percentage) {
		this.percentage = percentage;
	}

	@Column(name = "ave_im", nullable = false, precision = 22, scale = 0)
	public double getAveIm() {
		return this.aveIm;
	}

	public void setAveIm(double aveIm) {
		this.aveIm = aveIm;
	}

	@Column(name = "area_ave_im", nullable = false, precision = 22, scale = 0)
	public double getAreaAveIm() {
		return this.areaAveIm;
	}

	public void setAreaAveIm(double areaAveIm) {
		this.areaAveIm = areaAveIm;
	}

	@Column(name = "ave_con", nullable = false, precision = 22, scale = 0)
	public double getAveCon() {
		return this.aveCon;
	}

	public void setAveCon(double aveCon) {
		this.aveCon = aveCon;
	}

	@Column(name = "area_ave_con", nullable = false, precision = 22, scale = 0)
	public double getAreaAveCon() {
		return this.areaAveCon;
	}

	public void setAreaAveCon(double areaAveCon) {
		this.areaAveCon = areaAveCon;
	}

}
