package model;

// Generated 2016-1-22 13:28:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SickList generated by hbm2java
 */
@Entity
@Table(name = "sickList")
public class SickList implements java.io.Serializable {

	private int index;
	private Integer secondId;
	private String secondName;
	private Double zonghe;
	private Double importanceAve;
	private Double protectiveAve;

	public SickList() {
	}

	public SickList(int index) {
		this.index = index;
	}

	public SickList(int index, Integer secondId, String secondName,
			Double zonghe, Double importanceAve, Double protectiveAve) {
		this.index = index;
		this.secondId = secondId;
		this.secondName = secondName;
		this.zonghe = zonghe;
		this.importanceAve = importanceAve;
		this.protectiveAve = protectiveAve;
	}

	@Id
	@Column(name = "index", unique = true, nullable = false)
	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	@Column(name = "secondId")
	public Integer getSecondId() {
		return this.secondId;
	}

	public void setSecondId(Integer secondId) {
		this.secondId = secondId;
	}

	@Column(name = "secondName")
	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	@Column(name = "zonghe", precision = 22, scale = 0)
	public Double getZonghe() {
		return this.zonghe;
	}

	public void setZonghe(Double zonghe) {
		this.zonghe = zonghe;
	}

	@Column(name = "importanceAve", precision = 22, scale = 0)
	public Double getImportanceAve() {
		return this.importanceAve;
	}

	public void setImportanceAve(Double importanceAve) {
		this.importanceAve = importanceAve;
	}

	@Column(name = "protectiveAve", precision = 22, scale = 0)
	public Double getProtectiveAve() {
		return this.protectiveAve;
	}

	public void setProtectiveAve(Double protectiveAve) {
		this.protectiveAve = protectiveAve;
	}

}
