package model;

// Generated 2015-12-11 16:56:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Top20 generated by hbm2java
 */
@Entity
@Table(name = "top20")
public class Top20 implements java.io.Serializable {

	private Integer id;
	private Integer sickId;

	public Top20() {
	}

	public Top20(Integer sickId) {
		this.sickId = sickId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sick_id")
	public Integer getSickId() {
		return this.sickId;
	}

	public void setSickId(Integer sickId) {
		this.sickId = sickId;
	}

}
